### ISSUE TITLE
How to make Twilio + Iron app for windows phone 7

### ISSUE THREAD

**Issue by emp123** [iron-io/issues#32]
I want to know that how can I make an app which will make a call on user's mobile at predefined time using twilio and iron.

**Comment by treeder** [comment]
Hi @emp123 , you can check out this blog post: http://blog.iron.io/2012/10/how-to-schedule-sms-and-calls-on-twilio.html

It really doesn't matter what type of phone they are using, you can initiate a call to any phone. Also, you can use those Ruby examples even if your app is in a different language since they run separately from your app, you just queue/schedule them via our HTTP api: http://dev.iron.io/worker/reference/api/#queue_a_task

Let me know if you need more help.

**Comment by emp123** [comment]
Hi treeder! Thanks for reply.
Actually I am not getting how to do this for windows phone 7? Should I write my logic on Iron + Twilio app at Iron.Io? But in that case I have a problem that is I want user will set Date and Time or Time parameter through his/her Windows Phone 7 device and at that time a call will schedule in my Twilio + Iron app and at that time a call (incoming call) will go  on user's device. Can you suggest me how  to do this means a communication in between Windows Phone 7 device and Iron? Is it possible to do?

**Comment by treeder** [comment]
Hi @emp123 , try using this worker that you can out of the box, no coding required: https://github.com/treeder/twilio_worker

Just upload it to your account with `iron_worker upload https://github.com/treeder/twilio_worker/blob/master/twilio.worker` 

Then you can just post tasks via our HTTP api, see the README for the curl command or review the docs in my comment above.

**Comment by carimura** [comment]
Hey @emp123 -- closing this up as it's 4 months old and we like to keep feature requests / bugs in here...

We are happy to continue helping you on this issue if you'd like.. jump into live chat: http://get.iron.io/chat or send an email to support [at] iron.io
